# -*- coding: utf-8 -*-

import argparse
import os
import re
import time
import pandas as pd
from PIL import Image

import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader
from torchvision import transforms
from transformers import CLIPProcessor, CLIPModel
import numpy as np
import tqdm

# Define paths for the SLURM environment
BASE_DATA_DIR = "/groups/orentsur_group/work/omertole/mimic_data"
IMAGE_DIR = os.path.join(BASE_DATA_DIR, "official_data_iccv_final")

# Point directly to the preprocessed CSV files generated by preprocess.py
TRAIN_CSV_PATH = os.path.join(BASE_DATA_DIR, "mimic_cxr_processed_train.csv")
VAL_CSV_PATH = os.path.join(BASE_DATA_DIR, "mimic_cxr_processed_validate.csv")
DEFAULT_OUTPUT_MODEL_DIR = os.path.join(BASE_DATA_DIR, "/checkpoints/hard_clip_study_baseline")
MODEL_NAME = "openai/clip-vit-base-patch32"

BATCH_SIZE = 256
NUM_WORKERS = 4
LEARNING_RATE = 5e-6
WEIGHT_DECAY = 0.2
EPOCHS = 10  
PATIENCE = 2  # Number of epochs to wait for improvement before stopping


def parse_args():
    parser = argparse.ArgumentParser(description="Fine-tune and/or evaluate a CLIP baseline on MIMIC-CXR.")
    parser.add_argument(
        "--mode",
        choices=["train", "eval", "both"],
        default="both",
        help="Run only training, only evaluation, or both (default: both).",
    )
    parser.add_argument(
        "--checkpoint",
        default=DEFAULT_OUTPUT_MODEL_DIR,
        help="Model directory to load for eval-only mode (default: saved baseline output dir).",
    )
    return parser.parse_args()


class MimicCLIPDataset(Dataset):
    def __init__(self, dataframe, base_image_dir):
        self.df = dataframe
        self.base_dir = base_image_dir
        self.transform = transforms.Compose([
            transforms.Resize((224, 224)),
            transforms.ToTensor(),
            transforms.Normalize(mean=[0.48145466, 0.4578275, 0.40821073],
                                 std=[0.26862954, 0.26130258, 0.27577711])
        ])

    def __len__(self):
        return len(self.df)

    def __getitem__(self, idx):
        current_idx = idx

        while True:
            img_path_rel = self.df.iloc[current_idx]['image']
            img_path_full = os.path.join(self.base_dir, img_path_rel)
            text_signal = self.df.iloc[current_idx]['impression_clean']

            if os.path.exists(img_path_full):
                try:
                    image = Image.open(img_path_full).convert('RGB')
                    image = self.transform(image)

                    # Extract study_id directly from the string path (e.g., 's50414267')
                    match = re.search(r'/s(\d+)/', img_path_rel)
                    study_id = match.group(1) if match else "unknown"

                    return image, text_signal, study_id

                except Exception:
                    pass # Skip to fallback if file is corrupted

            # Fallback strategy: try previous index
            current_idx = (current_idx - 1) % len(self.df)


def study_level_contrastive_loss(image_features, text_features, logit_scale, study_ids):
    """
    Computes Supervised Contrastive Loss at the study level.
    Treats any text/image from the same study_id in the batch as a valid positive pair.
    """
    device = image_features.device

    # L2 Normalize embeddings to unit vectors
    image_features = image_features / image_features.norm(dim=-1, keepdim=True)
    text_features = text_features / text_features.norm(dim=-1, keepdim=True)

    # Calculate scaled cosine similarities
    scale = logit_scale.exp()
    logits_per_image = scale * torch.matmul(image_features, text_features.t())
    logits_per_text = logits_per_image.t()

    # Create boolean mask for positive pairs based on identical study_ids
    study_ids_np = np.array(study_ids)
    mask_np = (study_ids_np[:, None] == study_ids_np[None, :])
    mask = torch.tensor(mask_np, dtype=torch.float32, device=device)

    # Calculate log-softmax for both directions
    log_probs_img = F.log_softmax(logits_per_image, dim=1)
    log_probs_txt = F.log_softmax(logits_per_text, dim=1)

    # Average the log-probabilities of all positive pairs per row
    positives_per_row = mask.sum(dim=1)
    loss_img = -(log_probs_img * mask).sum(dim=1) / positives_per_row
    loss_txt = -(log_probs_txt * mask).sum(dim=1) / positives_per_row

    # Return symmetric average
    return (loss_img.mean() + loss_txt.mean()) / 2


def get_study_id(image_path):
    match = re.search(r'/s(\d+)/', image_path)
    return match.group(1) if match else "unknown"


def calculate_study_level_metrics(sim_matrix, study_ids):
    sim_matrix_np = sim_matrix.cpu().numpy()
    r1, r5, r10, mrr = 0.0, 0.0, 0.0, 0.0
    ranks = []
    num_queries = sim_matrix_np.shape[0]

    for i in range(num_queries):
        query_study = study_ids[i]
        sorted_indices = np.argsort(-sim_matrix_np[i])
        retrieved_studies = study_ids[sorted_indices]
        matches = (retrieved_studies == query_study)

        first_match_rank = np.where(matches)[0][0] + 1
        ranks.append(first_match_rank)

        if first_match_rank <= 1: r1 += 1
        if first_match_rank <= 5: r5 += 1
        if first_match_rank <= 10: r10 += 1
        mrr += 1.0 / first_match_rank

    return (r1/num_queries)*100, (r5/num_queries)*100, (r10/num_queries)*100, np.median(ranks), mrr/num_queries


def load_model_and_processor(checkpoint=None):
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    source = checkpoint or MODEL_NAME
    processor = CLIPProcessor.from_pretrained(source)
    model = CLIPModel.from_pretrained(source)
    model = model.to(device)
    print(f"CLIP model loaded from {source} on device: {device}")
    return model, processor, device


def build_dataloaders(mode):
    df_train_flat = None
    
    # Load preprocessed validation dataset directly
    print(f"Loading preprocessed validation dataset from: {VAL_CSV_PATH}")
    df_val_flat = pd.read_csv(VAL_CSV_PATH).fillna("")

    train_loader = None
    if mode in ("train", "both"):
        # Load preprocessed training dataset directly
        print(f"Loading preprocessed training dataset from: {TRAIN_CSV_PATH}")
        df_train_flat = pd.read_csv(TRAIN_CSV_PATH).fillna("")
        
        train_dataset = MimicCLIPDataset(df_train_flat, IMAGE_DIR)
        train_loader = DataLoader(
            dataset=train_dataset,
            batch_size=BATCH_SIZE,
            shuffle=True,
            num_workers=NUM_WORKERS,
            pin_memory=True,
        )

    val_dataset = MimicCLIPDataset(df_val_flat, IMAGE_DIR)
    val_loader = DataLoader(
        dataset=val_dataset,
        batch_size=BATCH_SIZE,
        shuffle=False,
        num_workers=NUM_WORKERS,
        pin_memory=True,
    )
    return train_loader, val_loader, df_val_flat


def run_training(model, processor, device, train_loader, val_loader):
    optimizer = torch.optim.AdamW(
        model.parameters(),
        lr=LEARNING_RATE,
        weight_decay=WEIGHT_DECAY,
    )

    print("Beginning execution of fine-tuning loop...")

    best_val_loss = float('inf')
    epochs_without_improvement = 0

    for epoch in range(EPOCHS):
        model.train()
        train_loss = 0.0
        start_time = time.time()

        for batch_idx, (images, texts, study_ids) in enumerate(train_loader):
            optimizer.zero_grad()

            text_inputs = processor(text=list(texts), return_tensors="pt", padding=True, truncation=True, max_length=77)
            input_ids = text_inputs['input_ids'].to(device)
            attention_mask = text_inputs['attention_mask'].to(device)
            pixel_values = images.to(device)

            image_outputs = model.get_image_features(pixel_values=pixel_values)
            text_outputs = model.get_text_features(input_ids=input_ids, attention_mask=attention_mask)

            image_features = image_outputs.pooler_output if hasattr(image_outputs, 'pooler_output') else image_outputs
            text_features = text_outputs.pooler_output if hasattr(text_outputs, 'pooler_output') else text_outputs

            loss = study_level_contrastive_loss(image_features, text_features, model.logit_scale, study_ids)
            loss.backward()
            optimizer.step()

            train_loss += loss.item()
            if batch_idx % 50 == 0:
                print(f"Epoch [{epoch+1}/{EPOCHS}] | Train Step [{batch_idx}/{len(train_loader)}] | Loss: {loss.item():.4f}")

        avg_train_loss = train_loss / len(train_loader)

        model.eval()
        val_loss = 0.0
        with torch.no_grad():
            for images, texts, study_ids in val_loader:
                text_inputs = processor(text=list(texts), return_tensors="pt", padding=True, truncation=True, max_length=77)
                input_ids = text_inputs['input_ids'].to(device)
                attention_mask = text_inputs['attention_mask'].to(device)
                pixel_values = images.to(device)

                image_outputs = model.get_image_features(pixel_values=pixel_values)
                text_outputs = model.get_text_features(input_ids=input_ids, attention_mask=attention_mask)

                image_features = image_outputs.pooler_output if hasattr(image_outputs, 'pooler_output') else image_outputs
                text_features = text_outputs.pooler_output if hasattr(text_outputs, 'pooler_output') else text_outputs

                loss = study_level_contrastive_loss(image_features, text_features, model.logit_scale, study_ids)
                val_loss += loss.item()

        avg_val_loss = val_loss / len(val_loader)
        elapsed_time = time.time() - start_time

        print(f"\n=======================================================")
        print(f"Epoch {epoch+1} Metrics:")
        print(f"-> Average Train Loss: {avg_train_loss:.4f}")
        print(f"-> Average Val Loss  : {avg_val_loss:.4f}")
        print(f"-> Time Taken        : {elapsed_time:.2f}s")
        print(f"=======================================================\n")

        if avg_val_loss < best_val_loss:
            best_val_loss = avg_val_loss
            epochs_without_improvement = 0
            
            os.makedirs(DEFAULT_OUTPUT_MODEL_DIR, exist_ok=True)
            model.save_pretrained(DEFAULT_OUTPUT_MODEL_DIR)
            processor.save_pretrained(DEFAULT_OUTPUT_MODEL_DIR)
            print(f"New best validation loss achieved. Model checkpoint successfully stored at {DEFAULT_OUTPUT_MODEL_DIR}\n")
        else:
            epochs_without_improvement += 1
            print(f"Validation loss did not improve. Early stopping counter: {epochs_without_improvement}/{PATIENCE}\n")
            
            if epochs_without_improvement >= PATIENCE:
                print(f"Early stopping condition triggered. Terminating training at Epoch {epoch+1}.")
                break


def run_evaluation(model, processor, device, val_loader, df_val_flat):
    model.eval()

    all_image_features = []
    all_text_features = []

    print("Extracting features for the Validation Set for Evaluation...")
    with torch.no_grad():
        for images, texts, _ in tqdm.tqdm(val_loader, desc="Validation Batches"):
            text_inputs = processor(text=list(texts), return_tensors="pt", padding=True, truncation=True, max_length=77).to(device)
            pixel_values = images.to(device)

            image_outputs = model.get_image_features(pixel_values=pixel_values)
            text_outputs = model.get_text_features(**text_inputs)

            img_feats = image_outputs.pooler_output if hasattr(image_outputs, 'pooler_output') else image_outputs
            txt_feats = text_outputs.pooler_output if hasattr(text_outputs, 'pooler_output') else text_outputs

            img_feats = img_feats / img_feats.norm(dim=-1, keepdim=True)
            txt_feats = txt_feats / txt_feats.norm(dim=-1, keepdim=True)

            all_image_features.append(img_feats.cpu())
            all_text_features.append(txt_feats.cpu())

    all_image_features = torch.cat(all_image_features, dim=0).to(device)
    all_text_features = torch.cat(all_text_features, dim=0).to(device)

    print("\n--- Calculating Retrieval Metrics (Study-Level) ---")
    sim_matrix = torch.matmul(all_image_features, all_text_features.t())

    df_val_flat['study_id'] = df_val_flat['image'].apply(get_study_id)
    study_ids = df_val_flat['study_id'].values

    i2t_r1, i2t_r5, i2t_r10, i2t_medr, i2t_mrr = calculate_study_level_metrics(sim_matrix, study_ids)
    t2i_r1, t2i_r5, t2i_r10, t2i_medr, t2i_mrr = calculate_study_level_metrics(sim_matrix.t(), study_ids)

    print(f"\n[Image-to-Text Retrieval (Study-Level)]")
    print(f"Recall@1 : {i2t_r1:.2f}% | Recall@5 : {i2t_r5:.2f}% | Recall@10: {i2t_r10:.2f}% | Median R : {i2t_medr:.1f} | MRR: {i2t_mrr:.4f}")

    print(f"\n[Text-to-Image Retrieval (Study-Level)]")
    print(f"Recall@1 : {t2i_r1:.2f}% | Recall@5 : {t2i_r5:.2f}% | Recall@10: {t2i_r10:.2f}% | Median R : {t2i_medr:.1f} | MRR: {t2i_mrr:.4f}")
    print("==========================================\n")


def main():
    args = parse_args()
    print(f"Running in mode: {args.mode}")

    train_loader, val_loader, df_val_flat = build_dataloaders(args.mode)

    if args.mode == "eval":
        model, processor, device = load_model_and_processor(args.checkpoint)
    else:
        model, processor, device = load_model_and_processor()

    if args.mode in ("train", "both"):
        run_training(model, processor, device, train_loader, val_loader)

    if args.mode in ("eval", "both"):
        if args.mode == "both":
            model, processor, device = load_model_and_processor(DEFAULT_OUTPUT_MODEL_DIR)
        run_evaluation(model, processor, device, val_loader, df_val_flat)


if __name__ == "__main__":
    main()